### ISSUE TITLE
コーディネートバトル画面が表示されない

### ISSUE THREAD

**Issue by chiemi627** [enpitut/cynts#68]
# 状況
- 「好きなコーディネートを選ぶ」をクリックすると何も表示されない
  - http://210.140.68.52/coordinatesbattle/battle
# 実行環境
- OS: Mac OS X Yosemite 
- Browser : Google Chrome

**Comment by chiemi627** [comment]
もう一度アクセスをしたら

> You are not authorized to access that location.

と表示されました。ログインをしないとダメなんですね。

**Comment by tasuwo** [comment]
おそらくパスの問題もあると思いますので，修正します
ヘッダーのリンクは正しいはずですので，そちらからなら遊べるかと
しかし，いずれにしろユーザ登録が必要となります
ユーザ登録は http://210.140.68.52/users/signup から行えます

**Comment by chiemi627** [comment]
なるほど、ありがとう！
というわけで早速ユーザ登録＆ログインしました。

が、やはり状況変わらず。
「好きなコーディネートを選ぶ」を押すと真っ白、な状態は変わりません。

確かにヘッダーのリンク（「Play」かな？）からは飛べますね！
遊んでみます。

**Comment by metalunk** [comment]
直ってたので close
