### ISSUE TITLE
コーデバトルが進行しなくなる

### ISSUE THREAD

**Issue by tasuwo** [enpitut/cynts#99]
再現方法
1. 条件付きでコーデバトルを行う(キャッシュする)
2. 条件に該当するコーデを削除する
3. 同じ条件でコーデバトルを行う
4. 画像を押下しても反応しなくなる

**Comment by tasuwo** [comment]
コーデバトルは以下の順で行われていて
新しいコーデを取得する`getNewCoordinate` と `getScore` の両方でDBにアクセスしているので，`getNewCoordinate` で

**Comment by tasuwo** [comment]
新しいコーデの取得時とコーデのスコア計算時に DB にアクセスしようとしていて，現在はコーデ取得時のみ検索条件でキャッシュするようになってる．
だから，キャッシュ後にコーデが削除されると，削除されてるコーデがキャッシュから持ってこられて，スコア計算時に参照しようとするとエラーになる．
だから，スコア計算時にもキャッシュの情報参照すれば良いのだけど，キャッシュは検索条件毎に一意のキー生成してファイルに保存されているから，コーデバトルの A側 と B側 は各々違うキャッシュからデータを引っ張ってきてる可能性があって，スコア計算時にどのキャッシュからデータをひっぱってくればいいかわからないのが問題．
でも，そもそも削除されたデータにアクセスしてバトルしようとしているのが問題なので，そこらへんはキャッシュの duration をうまく調整するということにして，万が一スコア計算時に存在しないコーデにアクセスしてしまった場合は，バトルとしては無効票のように扱うというのがいいかも．

ということで，そういった対応できるように改善したいと思います．

**Comment by metalunk** [comment]
一つのアイディアとしてはコーディネートを削除する際に，今は物理削除しているけど，それを止めて論理削除するようにすればいいかなあ
そのために status カラム作っといたからね（status カラム作ったくせにめんどくさがって物理削除を実装したのはおれ）

コーディネートを削除した人からすると，すぐには削除されないけど，最大キャッシュ時間分たてば基本的には参照されなくなるから，それを了承してねって削除の時に出しておけばおk

具体的には削除するときは `status = Coordinates::STATUS::DELETED;` して，コーディネートを引っ張ってくるときは status の絞り込みも追加しておけば良さそう
で，コーディネートバトルのときは例外的に status を気にせずに取得すると

コーディネート引っ張ってくるところそんなにないからまだ簡単に置換できそうだし

**Comment by tasuwo** [comment]
あーなるほど
今はとりあえず，削除されたコーデに関わるバトルは完全に無視されるようになってて結果にも反映されない(ようにした)んだけど，それだと「バトル終了」ボタンでてくるのに結果が一つもなかったり(ありえないけど)，押下したはずのコーデが結果に出てこなかったりするから，そっちの方がいいね！

今日中に修正できるように頑張ります．

**Comment by tasuwo** [comment]
あ，でも，結果画面に既に削除されたコーデが表示されてしまうのはまずい？それをやらないのであれば結局バトル中に既に削除されたコーデが出てきても無視することになっちゃうし，今のコミットからわざわざ論理削除に変更する必要もないかなって思うんだけど，どうでしょう

優先度高くなければ他の積まれてるタスク進めちゃおうかな
